# Generated by Django 5.0.1 on 2024-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='Somalia', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='Mogadishu', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='banaadir', max_length=50),
        ),
    ]
